### ISSUE TITLE
Cannot input the + symbol in the phone number field when inputting billing details

### ISSUE THREAD

**Issue by harryblam** [checkout/frames-ios#10] opened 2020-01-02 17:55 UTC
**Describe the bug**
When using the `billingDetailsPhone` state as required, I cannot input the + symbol in the phone number field.

**To Reproduce**
1. Initialise the view with `cardHolderNameState: .required, billingDetailsState: .required`
2. Enter all required details
3. Go to billing details view
4. Enter all required fields, and try to enter phone number as +442312312321
5. Observe the + doesn't get populated and an error shows 

**Expected behavior**
In #5 from the above, it will allow entering + symbol

**Screenshots**
![IMG_A82953FC59A7-1](https://user-images.githubusercontent.com/2333536/71682922-666abb00-2d91-11ea-85d6-b81833cc362c.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.3

**Comment by zhiyilee** [comment] 2020-06-05 01:04
Same here

**Comment by daven-gomes-cko** [comment] 2021-03-15 18:15
Hi @harryblam sorry for the late reply. I can't seem to reproduce this issue, it may have been fixed in a release since this issue was opened, or when we updated `PhoneNumberKit`.

![simulator_screenshot_244A62FB-BAB5-4D03-B978-2D87D0152F47](https://user-images.githubusercontent.com/59568833/111201180-6d5aa380-85ba-11eb-9e11-c3375c81c850.png)

If you still experience this bug please feel free to re-open this issue. Thanks.

**Closed by daven-gomes-cko** 2021-03-15 18:15 UTC
