### ISSUE TITLE
Delegate method  of view controllers not called

### ISSUE THREAD

**Issue by SalilLuley** [checkout/frames-ios#18] opened 2020-06-14 05:50 UTC
Just copy pasted the kick start frames code in iOS GitHub  repo. In that I found a bug that cardViewController.delegate = self does not set the delegate, its still nil and because of that delegate methods of my vc are not called from CardViewController.

**Comment by daven-gomes-cko** [comment] 2020-06-15 13:44
I've just tried to run the code and it appears to work as expected, calling the delegate method as expected after entering some test card details and tapping the Pay button.  Do you mean this isn't working for you when you run the sample code?  Or it isn't working in your project?

If you could please post some sample code it might help see where the issue is.

**Comment by dhavalgajjar-greenapex** [comment] 2020-06-19 12:35
I am facing the same issue.
I just copy and pasted in my project by referring GitHub home page's document.  
Using pod 'Frames', '~> 3.0'.
Delegate is nil even after assigning viewcontroller and not getting call back.

Step 1: 
private let checkoutAPIClient = CheckoutAPIClient(publicKey: "public_key",
    environment: .sandbox)

Step 2 : 
private var cardViewController: CardViewController {
        let checkoutAPIClient = CheckoutAPIClient(publicKey: "publc_key",
        environment: .sandbox)
        return CardViewController(checkoutApiClient: checkoutAPIClient, cardHolderNameState: .hidden, billingDetailsState: .hidden)
    }

Step 3: 
ViewdidLoad : 

cardViewController.delegate = self
cardViewController.rightBarButtonItem = UIBarButtonItem(title: "Pay", style: .done, target: nil, action: nil)
cardViewController.availableSchemes = [.visa, .mastercard , .americanExpress , .discover , .unionPay, .maestro]
  
Step 4 : 
self.navigationController?.pushViewController(cardViewController, animated: true)

Step 5:  Handling delegate methods

extension Viewcontroller : CardViewControllerDelegate {
    func onSubmit(controller: CardViewController) {
        print("Submited")
    }
    
func onTapDone(controller: CardViewController, cardToken: CkoCardTokenResponse?, status: CheckoutTokenStatus) {
        print("onTapDone")
    }
}

**Comment by daven-gomes-cko** [comment] 2020-06-19 14:56
@dhavalgajjar-greenapex Could you try change your `cardViewController` to `lazy var`.  From your code, it appears every time you call `cardViewController`, you are creating a new instance rather than retaining one.

**Comment by daven-gomes-cko** [comment] 2020-06-26 13:34
Closing this issue for now, if you still experience this problem or the above solution does not work, feel free to re-open it.

**Closed by daven-gomes-cko** 2020-06-26 13:34 UTC

**Comment by SalilLuley** [comment] 2020-07-01 15:03
Initialising `cardViewController` as lazy var did the trick. Thank you for the help.
